services:
  - type: web
    name: goodlisteners-app
    env: docker
    healthCheckPath: /api/ping      # Add this line
    envVars:
      - key: DATABASE_PATH
        value: /data/goodlisteners.db
      - key: PORT
        value: 8080
    disk:
      name: data
      mountPath: /data
      sizeGB: 1