name: Java CI/CD Pipeline

on:
  push:
    branches:
      - main  # Executing pipeline for pushes
  pull_request:
    branches:
      - main  # Executing pipeline for pulls

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # Configuring JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Build
      - name: Build with Maven
        run: mvn clean install

      # Tests
      - name: Run tests
        run: mvn test

      # Deploy - TBD
      # - name: Deploy
      #   run: |
      #     scp target/my-app.jar user@yourserver:/path/to/deploy
